### ISSUE TITLE
13. Instagram info not working 

### ISSUE THREAD

**Issue by kuzuri-03** [evildevill/Hackerwasi#7]
Whenever I search for instagram info  ...
I recieved an error 
Traceback (most recent call last):
  File "Hackerwasi.py", line 220, in <module>
    searchInstagram()
  File "/root/Hackerwasi/core/searchInstagram.py", line 21, in searchInstagram
    images = shortCutUrl(images)
  File "/root/Hackerwasi/core/shortCutUrl.py", line 6, in shortCutUrl
    url = Url(url).decode()
  File "/root/Hackerwasi/lib/Url.py", line 47, in decode
    while '%' in url:
TypeError: argument of type 'NoneType' is not iterable

**Comment by evildevill** [comment]
@kuzuri-03 
I'll updated as soon as possible 😊🖤 thanks for telling us

**Comment by kuzuri-03** [comment]
ur welcome ...
I tried to fix it but it didn't work out ...inform me when uhh update it nd
it starts working...☺☺☺☺😊😊

**Comment by evildevill** [comment]
@kuzuri-03 
Hey Bro Hope you are fine and well , i updated the tool now it's working now you can use it  thanks for telling us🖤😘

**Comment by balrajsandhu007** [comment]
bro it say username not found

**Comment by kuzuri-03** [comment]
still not working 
Traceback (most recent call last):
  File "/root/Hackerwasi/Hackerwasi.py", line 220, in <module>
    searchInstagram()
  File "/root/Hackerwasi/core/searchInstagram.py", line 21, in searchInstagram
    images = shortCutUrl(images)
  File "/root/Hackerwasi/core/shortCutUrl.py", line 6, in shortCutUrl
    url = Url(url).decode()
  File "/root/Hackerwasi/lib/Url.py", line 47, in decode
    while '%' in url:
TypeError: argument of type 'NoneType' is not iterable
